# Generated by Django 3.2.16 on 2023-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_genrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='genre',
            field=models.CharField(default='Fiction', max_length=255),
            preserve_default=False,
        ),
    ]
