# Generated by Django 3.2.16 on 2023-02-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
