# Generated by Django 3.2.16 on 2023-04-22 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230228_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='director',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='release_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
