# Generated by Django 3.2.16 on 2023-04-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230422_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='release_at',
            field=models.DateField(),
        ),
    ]
