# Generated by Django 3.2.16 on 2023-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posts_release_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='actors',
            field=models.CharField(default='No one', max_length=100),
            preserve_default=False,
        ),
    ]
